var annotated_dup =
[
    [ "Lightbug", "namespace_lightbug.html", [
      [ "CharacterControllerPro", "namespace_lightbug_1_1_character_controller_pro.html", [
        [ "Core", "namespace_lightbug_1_1_character_controller_pro_1_1_core.html", [
          [ "AnimatorLink", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_animator_link.html", null ],
          [ "CharacterActor", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_actor.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_actor" ],
          [ "CharacterBody", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_body.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_body" ],
          [ "CharacterCollisionInfo", "struct_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collision_info.html", "struct_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collision_info" ],
          [ "CharacterCollisions", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collisions.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collisions" ],
          [ "CharacterCollisions2D", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collisions2_d.html", null ],
          [ "CharacterCollisions3D", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_collisions3_d.html", null ],
          [ "CharacterConstants", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_constants.html", null ],
          [ "CharacterDebug", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_debug.html", null ],
          [ "CharacterDetector", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_detector.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_detector" ],
          [ "CharacterGraphics", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_graphics.html", null ],
          [ "CharacterGraphics2DRotator", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_graphics2_d_rotator.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_graphics2_d_rotator" ],
          [ "CharacterGraphicsRootController", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_graphics_root_controller.html", null ],
          [ "CharacterGraphicsScaler", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_graphics_scaler.html", null ],
          [ "CharacterRotationLerper", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_rotation_lerper.html", null ],
          [ "CharacterSpriteRotator", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_sprite_rotator.html", null ],
          [ "CharacterStepLerper", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_character_step_lerper.html", null ],
          [ "CollisionInfo", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_collision_info.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_collision_info" ],
          [ "DynamicOneWayPlatform", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_dynamic_one_way_platform.html", null ],
          [ "PhysicsActor", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_physics_actor.html", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_physics_actor" ],
          [ "PhysicsActorSync", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_physics_actor_sync.html", null ],
          [ "VerticalAlignmentSettings", "class_lightbug_1_1_character_controller_pro_1_1_core_1_1_vertical_alignment_settings.html", null ]
        ] ],
        [ "Implementation", "namespace_lightbug_1_1_character_controller_pro_1_1_implementation.html", [
          [ "BoolAction", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_bool_action.html", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_bool_action" ],
          [ "CharacterActions", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_actions.html", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_actions" ],
          [ "CharacterActionsAsset", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_actions_asset.html", null ],
          [ "CharacterAIAction", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_a_i_action.html", null ],
          [ "CharacterAIBehaviour", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_a_i_behaviour.html", null ],
          [ "CharacterBrain", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_brain.html", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_brain" ],
          [ "CharacterState", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_state.html", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_state" ],
          [ "CharacterStateController", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_state_controller.html", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_character_state_controller" ],
          [ "FloatAction", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_float_action.html", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_float_action" ],
          [ "InputAxes", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_input_axes.html", null ],
          [ "InputButton", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_input_button.html", null ],
          [ "InputHandler", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_input_handler.html", null ],
          [ "InputHandlerSettings", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_input_handler_settings.html", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_input_handler_settings" ],
          [ "IUIAction", "interface_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_i_u_i_action.html", null ],
          [ "IUIBoolAction", "interface_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_i_u_i_bool_action.html", null ],
          [ "IUIFloatAction", "interface_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_i_u_i_float_action.html", null ],
          [ "IUIVector2Action", "interface_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_i_u_i_vector2_action.html", null ],
          [ "IUpdatable", "interface_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_i_updatable.html", null ],
          [ "MovementReferenceParameters", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_movement_reference_parameters.html", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_movement_reference_parameters" ],
          [ "UIInputHandler", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_u_i_input_handler.html", null ],
          [ "UnityInputHandler", "class_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_unity_input_handler.html", null ],
          [ "Vector2Action", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_vector2_action.html", "struct_lightbug_1_1_character_controller_pro_1_1_implementation_1_1_vector2_action" ]
        ] ]
      ] ],
      [ "Utilities", "namespace_lightbug_1_1_utilities.html", [
        [ "ActionAttribute", "class_lightbug_1_1_utilities_1_1_action_attribute.html", null ],
        [ "BooleanButtonAttribute", "class_lightbug_1_1_utilities_1_1_boolean_button_attribute.html", null ],
        [ "BoxColliderComponent2D", "class_lightbug_1_1_utilities_1_1_box_collider_component2_d.html", null ],
        [ "BoxColliderComponent3D", "class_lightbug_1_1_utilities_1_1_box_collider_component3_d.html", null ],
        [ "BreakVector2Attribute", "class_lightbug_1_1_utilities_1_1_break_vector2_attribute.html", null ],
        [ "BreakVector3Attribute", "class_lightbug_1_1_utilities_1_1_break_vector3_attribute.html", null ],
        [ "CapsuleColliderComponent2D", "class_lightbug_1_1_utilities_1_1_capsule_collider_component2_d.html", null ],
        [ "CapsuleColliderComponent3D", "class_lightbug_1_1_utilities_1_1_capsule_collider_component3_d.html", null ],
        [ "ColliderComponent", "class_lightbug_1_1_utilities_1_1_collider_component.html", "class_lightbug_1_1_utilities_1_1_collider_component" ],
        [ "ColliderComponent2D", "class_lightbug_1_1_utilities_1_1_collider_component2_d.html", "class_lightbug_1_1_utilities_1_1_collider_component2_d" ],
        [ "ColliderComponent3D", "class_lightbug_1_1_utilities_1_1_collider_component3_d.html", "class_lightbug_1_1_utilities_1_1_collider_component3_d" ],
        [ "ConditionAttribute", "class_lightbug_1_1_utilities_1_1_condition_attribute.html", "class_lightbug_1_1_utilities_1_1_condition_attribute" ],
        [ "Contact", "struct_lightbug_1_1_utilities_1_1_contact.html", "struct_lightbug_1_1_utilities_1_1_contact" ],
        [ "CustomClassDrawer", "class_lightbug_1_1_utilities_1_1_custom_class_drawer.html", null ],
        [ "CustomHeaderAttribute", "class_lightbug_1_1_utilities_1_1_custom_header_attribute.html", null ],
        [ "ExpandAttribute", "class_lightbug_1_1_utilities_1_1_expand_attribute.html", null ],
        [ "HelpBoxAttribute", "class_lightbug_1_1_utilities_1_1_help_box_attribute.html", null ],
        [ "HitInfo", "struct_lightbug_1_1_utilities_1_1_hit_info.html", null ],
        [ "HitInfoFilter", "struct_lightbug_1_1_utilities_1_1_hit_info_filter.html", null ],
        [ "PhysicsComponent", "class_lightbug_1_1_utilities_1_1_physics_component.html", "class_lightbug_1_1_utilities_1_1_physics_component" ],
        [ "PhysicsComponent2D", "class_lightbug_1_1_utilities_1_1_physics_component2_d.html", "class_lightbug_1_1_utilities_1_1_physics_component2_d" ],
        [ "PhysicsComponent3D", "class_lightbug_1_1_utilities_1_1_physics_component3_d.html", "class_lightbug_1_1_utilities_1_1_physics_component3_d" ],
        [ "ReadOnlyAttribute", "class_lightbug_1_1_utilities_1_1_read_only_attribute.html", null ],
        [ "RigidbodyComponent", "class_lightbug_1_1_utilities_1_1_rigidbody_component.html", "class_lightbug_1_1_utilities_1_1_rigidbody_component" ],
        [ "RigidbodyComponent2D", "class_lightbug_1_1_utilities_1_1_rigidbody_component2_d.html", "class_lightbug_1_1_utilities_1_1_rigidbody_component2_d" ],
        [ "RigidbodyComponent3D", "class_lightbug_1_1_utilities_1_1_rigidbody_component3_d.html", "class_lightbug_1_1_utilities_1_1_rigidbody_component3_d" ],
        [ "SphereColliderComponent2D", "class_lightbug_1_1_utilities_1_1_sphere_collider_component2_d.html", null ],
        [ "SphereColliderComponent3D", "class_lightbug_1_1_utilities_1_1_sphere_collider_component3_d.html", null ],
        [ "Trigger", "struct_lightbug_1_1_utilities_1_1_trigger.html", "struct_lightbug_1_1_utilities_1_1_trigger" ]
      ] ]
    ] ]
];